version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: podcast-creator
    container_name: podcast-creator
    volumes:
      - /Volumes/Samsung_T5/Podcast_Episoden:/app/data/Podcast_Episoden 
      - ./data/transcripts.sqlite:/app/data/transcripts.sqlite
    env_file:
      - .docker_env  
    ports:
      - "8000:8000"  
    # secrets:
    #   token:
    #     environment: "OPENAI_KEY"
