FROM python:3.8.10

RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app

COPY docker_requirements.txt .
RUN pip install -r docker_requirements.txt

RUN mkdir /app/data
RUN mkdir /app/data/Podcast_Episoden
RUN mkdir /app/data/audio_segments

ENV PYTHONPATH=/app/scripts

COPY .docker_env .env
COPY scripts /app/scripts
COPY data/matrices /app/data/matrices

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "scripts.server.app:app"]


