apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: web
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: web
        app.kubernetes.io/name: web
    spec:
      containers:
      - name: web
        image: '{{ .Context.Build.Image "webserver" }}'
        ports:
        - name: web-port
          containerPort: 8080
        env:
        - name: CHROMADB_HOST
          value: 'chromadb'
        - name: CHROMADB_PORT
          value: '8000'
        - name: OPENAI_KEY
          valueFrom:
            secretKeyRef:
              name: openai
              key: key
        - name: DATABASE_PATH
          value: /app/data/transcripts.sqlite
        - name: DATA_PATH
          value: /app/data/
        - name: AUDIO_SOURCE_PATH
          value: /app/data/Podcast_Episoden
        - name: AUDIO_SEGMENT_PATH
          value: /app/data/audio_segments
        - name: SERVER_PATH
          value: /app/scripts/server
        volumeMounts:
        - name: db
          mountPath: /app/data
        - name: audio
          mountPath: /app/scripts/server/static/audio
        resources:
          requests:
            memory: 5Gi
            cpu: 2
          limits:
            memory: 5Gi
      volumes:
      - name: audio
        emptyDir:
          sizeLimit: 5Gi
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
