apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/instance: web
    app.kubernetes.io/name: web
spec:
  ports:
  - port: 8080
    targetPort: web-port
    protocol: TCP
  selector:
    app.kubernetes.io/instance: web
    app.kubernetes.io/name: web
