version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: podcast-creator_on_demand_3
    container_name: podcast-creator_on_demand_3
    # volumes:
    #   - /Volumes/Samsung_T5/Podcast_Episoden:/app/data/Podcast_Episoden 
    #   - ./data/transcripts.sqlite:/app/data/transcripts.sqlite
    env_file:
      - .docker_env  
    ports:
      - "8080:8080"  
    # secrets:
    #   token:
    #     environment: "OPENAI_KEY"
