FROM python:3.8.10

WORKDIR /app

# RUN apk update && \
#     apk add --no-cache git ffmpeg sqlite

RUN apt-get update && apt-get install -y ffmpeg
RUN apt-get install sqlite3 

COPY docker_requirements.txt .
RUN pip install -r docker_requirements.txt

RUN mkdir /app/data
RUN mkdir /app/data/Podcast_Episoden
RUN mkdir /app/data/audio_segments



ENV PYTHONPATH=/app/scripts

COPY .docker_env .env
COPY docker_start.sh docker_start.sh
COPY scripts /app/scripts
COPY data/matrices /app/data/matrices
COPY data/inter.wav /app/data/inter.wav
COPY data/transcripts.sqlite /app/data/transcripts.sqlite
COPY data/german.dic /app/data/german.dic
COPY data/chromadb /app/data/


CMD docker_start.sh


